import type { Country, Point, RealmTheme, Settlement, SettlementKind, Tile, TileKind, WorldFeature, WorldMap } from './types';

export const TILE_SIZE = 48;
export const MAP_WIDTH = 480;
export const MAP_HEIGHT = 192;
const blocked = new Set<TileKind>(['water', 'rock', 'hill', 'house']);
const realms: Array<Omit<Country, 'id'>> = [
  { name: 'Alderwyn', theme: 'highland', color: '#b95747', banner: '#f0c674' },
  { name: 'Thornmere', theme: 'forest', color: '#4c8763', banner: '#d6e2a4' },
  { name: 'Valedorn', theme: 'river', color: '#4d7da8', banner: '#e7d7a2' },
  { name: 'Caerwyn', theme: 'coastal', color: '#8a638e', banner: '#f0b27a' },
  { name: 'Sungate Marches', theme: 'marches', color: '#b98640', banner: '#f7df8d' },
];
const settlementNames: Record<SettlementKind, string[]> = {
  capital: ['Highcourt', 'Greenglen', 'Rivercrown', 'Seaward', 'Goldwatch'],
  city: ['Briarhold', 'Mossford', 'Larkspur', 'Dunwall', 'Brightmere', 'Oakrest', 'Kingscross', 'Fairhaven', 'Willowgate', 'Amberfield', 'Stonebridge', 'Roseward'],
  village: ['Ashbrook', 'Cloverden', 'Fern Hollow', 'Littleford', 'Hearthstead', 'Pinecross', 'Millrun', 'Applewick', 'Dovefield', 'Brookhollow', 'Foxglove', 'Tansy Vale', 'Wrenfield', 'Meadowrun', 'Glimmerfen'],
};
const dimensions: Record<SettlementKind, number> = { village: 13, city: 21, capital: 29 };

export function createMap(seed = 7331): WorldMap {
  const tiles: Tile[] = []; let state = seed >>> 0; const random = () => { state = (1664525 * state + 1013904223) >>> 0; return state / 0x100000000; };
  const countries = realms.map((realm, index) => ({ ...realm, id: `realm-${index}` }));
  const countryAt = (col: number) => countries[Math.min(countries.length - 1, Math.floor(col / (MAP_WIDTH / countries.length)))];
  const terrainFor = (theme: RealmTheme, roll: number): TileKind => theme === 'highland' ? (roll < 0.11 ? 'rock' : roll < 0.34 ? 'hill' : roll < 0.5 ? 'forest' : 'grass') : theme === 'forest' ? (roll < 0.52 ? 'forest' : roll < 0.66 ? 'flower' : roll < 0.72 ? 'water' : 'grass') : theme === 'river' ? (roll < 0.14 ? 'water' : roll < 0.28 ? 'flower' : roll < 0.39 ? 'forest' : 'grass') : theme === 'coastal' ? (roll < 0.18 ? 'water' : roll < 0.28 ? 'sand' : roll < 0.42 ? 'flower' : 'grass') : (roll < 0.18 ? 'sand' : roll < 0.33 ? 'flower' : roll < 0.43 ? 'hill' : 'grass');
  for (let row = 0; row < MAP_HEIGHT; row += 1) for (let col = 0; col < MAP_WIDTH; col += 1) { const edge = col < 3 || row < 3 || col >= MAP_WIDTH - 3 || row >= MAP_HEIGHT - 3; const country = countryAt(col); const kind = edge ? 'water' : terrainFor(country.theme, random()); tiles.push({ col, row, kind, walkable: !blocked.has(kind), countryId: country.id }); }
  const at = (point: Point) => tiles[point.row * MAP_WIDTH + point.col]; const settlements: Settlement[] = []; const features: WorldFeature[] = [];
  const overlaps = (left: number, top: number, right: number, bottom: number) => settlements.some((s) => left <= s.bounds.right + 3 && right + 3 >= s.bounds.left && top <= s.bounds.bottom + 3 && bottom + 3 >= s.bounds.top);
  const addSettlement = (country: Country, kind: SettlementKind, col: number, row: number, name: string) => {
    const size = dimensions[kind]; const half = Math.floor(size / 2); const bounds = { left: col - half, top: row - half, right: col + half, bottom: row + half }; const settlement: Settlement = { id: `${country.id}-${kind}-${settlements.length}`, name, kind, countryId: country.id, col, row, radius: half, bounds, entrances: [{ col, row }] }; settlements.push(settlement);
    for (let y = bounds.top; y <= bounds.bottom; y += 1) for (let x = bounds.left; x <= bounds.right; x += 1) { if (x < 3 || y < 3 || x >= MAP_WIDTH - 3 || y >= MAP_HEIGHT - 3) continue; const tile = at({ col: x, row: y }); tile.kind = 'grass'; tile.walkable = true; tile.settlementId = settlement.id; }
    const ring = Math.floor(size / 2) - 3; for (let y = bounds.top + 2; y <= bounds.bottom - 2; y += 1) for (let x = bounds.left + 2; x <= bounds.right - 2; x += 1) { const dx = x - col; const dy = y - row; const distance = Math.max(Math.abs(dx), Math.abs(dy)); const gap = (x + y * 3 + settlement.id.length) % 5 === 0; if (distance >= ring - 1 && distance <= ring && !gap && Math.abs(dx) > 1 && Math.abs(dy) > 1) { const tile = at({ col: x, row: y }); tile.kind = 'house'; tile.walkable = false; } }
    for (let y = row - 2; y <= row + 2; y += 1) for (let x = col - 2; x <= col + 2; x += 1) { const tile = at({ col: x, row: y }); tile.kind = 'grass'; tile.walkable = true; tile.settlementId = settlement.id; } return settlement;
  };
  countries.forEach((country, index) => { const left = index * (MAP_WIDTH / countries.length) + 10; const right = (index + 1) * (MAP_WIDTH / countries.length) - 10; const center = Math.round((left + right) / 2); addSettlement(country, 'capital', center, index % 2 ? 142 : 50, settlementNames.capital[index]); addSettlement(country, 'city', left + 10, 82 + (index % 2) * 18, settlementNames.city[index * 2]); addSettlement(country, 'city', right - 10, 110 - (index % 2) * 18, settlementNames.city[index * 2 + 1]); if (index % 2 === 0) addSettlement(country, 'city', center, 155, settlementNames.city[10 + index / 2]); const anchors = settlements.filter((s) => s.countryId === country.id && s.kind !== 'village'); for (let village = 0; village < 6; village += 1) { const anchor = anchors[village % anchors.length]; let col = anchor.col + (village % 2 ? -9 : 9); let row = anchor.row + (village < 3 ? 15 : -15); let tries = 0; while (tries < 20 && (overlaps(col - 6, row - 6, col + 6, row + 6) || col < left + 7 || col > right - 7 || row < 10 || row > MAP_HEIGHT - 10)) { col += tries % 2 ? 3 : -3; row += tries % 3 ? 2 : -2; tries += 1; } addSettlement(country, 'village', col, row, settlementNames.village[index * 3 + village % 3]); } });
  const route = (from: Point, to: Point, sourceId: string, targetId: string) => { const key = (p: Point) => `${p.col},${p.row}`; const minCol = Math.max(3, Math.min(from.col, to.col) - 32); const maxCol = Math.min(MAP_WIDTH - 4, Math.max(from.col, to.col) + 32); const minRow = Math.max(3, Math.min(from.row, to.row) - 32); const maxRow = Math.min(MAP_HEIGHT - 4, Math.max(from.row, to.row) + 32); const queue = [from]; let head = 0; const came = new Map<string, Point>(); const seen = new Set([key(from)]); const steps = [{ col: Math.sign(to.col - from.col), row: 0 }, { col: 0, row: Math.sign(to.row - from.row) }, { col: 1, row: 0 }, { col: -1, row: 0 }, { col: 0, row: 1 }, { col: 0, row: -1 }].filter((step) => step.col || step.row); while (head < queue.length) { const current = queue[head++]; if (current.col === to.col && current.row === to.row) break; for (const step of steps) { const next = { col: current.col + step.col, row: current.row + step.row }; const tile = at(next); const nextKey = key(next); if (!tile || next.col < minCol || next.col > maxCol || next.row < minRow || next.row > maxRow || seen.has(nextKey) || tile.kind === 'house' || (tile.settlementId && tile.settlementId !== sourceId && tile.settlementId !== targetId)) continue; seen.add(nextKey); came.set(nextKey, current); queue.push(next); } } const path: Point[] = []; let cursor = to; while (key(cursor) !== key(from) && came.has(key(cursor))) { path.unshift(cursor); cursor = came.get(key(cursor))!; } return path; };
  const carveRoad = (from: Settlement, to: Settlement) => { const path = route(from, to, from.id, to.id); for (const point of path) { const tile = at(point); if (tile.kind !== 'road' && tile.kind !== 'bridge') { tile.groundKind = tile.kind; tile.kind = tile.groundKind === 'water' ? 'bridge' : 'road'; } tile.walkable = true; } from.entrances.push(path[0] ?? from); to.entrances.push(path[path.length - 1] ?? to); };
  countries.forEach((country, index) => { const own = settlements.filter((s) => s.countryId === country.id); const capital = own.find((s) => s.kind === 'capital')!; const cities = own.filter((s) => s.kind === 'city'); cities.forEach((city) => carveRoad(capital, city)); own.filter((s) => s.kind === 'village').forEach((village, villageIndex) => carveRoad(village, cities[villageIndex % cities.length])); if (index > 0) { const previous = settlements.find((s) => s.countryId === countries[index - 1].id && s.kind === 'capital')!; carveRoad(previous, capital); features.push({ col: Math.floor(index * MAP_WIDTH / countries.length), row: capital.row, kind: 'gate' }); } });
  for (let index = 1; index < countries.length; index += 1) for (let row = 20; row < MAP_HEIGHT - 20; row += 32) features.push({ col: Math.floor(index * MAP_WIDTH / countries.length), row, kind: 'frontier-marker' }); const startingVillage = settlements.find((s) => s.countryId === countries[0].id && s.kind === 'village')!; return { width: MAP_WIDTH, height: MAP_HEIGHT, tiles, spawn: { col: startingVillage.col, row: startingVillage.row }, countries, settlements, features };
}
export function tileAt(map: WorldMap, point: Point): Tile | undefined { return point.col >= 0 && point.row >= 0 && point.col < map.width && point.row < map.height ? map.tiles[point.row * map.width + point.col] : undefined; }
export function clampPoint(map: WorldMap, point: Point): Point { return { col: Math.max(0, Math.min(map.width - 1, point.col)), row: Math.max(0, Math.min(map.height - 1, point.row)) }; }
