import { clampPoint, tileAt } from './map';
import type { Point, WorldMap } from './types';

const directions = [-1, 0, 1].flatMap((row) => [-1, 0, 1].map((col) => ({ col, row }))).filter(({ col, row }) => col || row);
const key = (p: Point) => `${p.col},${p.row}`;
const distance = (a: Point, b: Point) => Math.hypot(a.col - b.col, a.row - b.row);
function neighbors(map: WorldMap, point: Point): Point[] { return directions.flatMap((step) => { const next = { col: point.col + step.col, row: point.row + step.row }; if (!tileAt(map, next)?.walkable) return []; if (step.col && step.row && (!tileAt(map, { col: point.col + step.col, row: point.row })?.walkable || !tileAt(map, { col: point.col, row: point.row + step.row })?.walkable)) return []; return [next]; }); }

export function reachableTiles(map: WorldMap, start: Point): Point[] { const queue = [start]; const seen = new Set([key(start)]); const result: Point[] = []; while (queue.length) { const current = queue.shift()!; result.push(current); for (const next of neighbors(map, current)) if (!seen.has(key(next))) { seen.add(key(next)); queue.push(next); } } return result; }
export function findPath(map: WorldMap, start: Point, goal: Point): Point[] | null { if (!tileAt(map, start)?.walkable || !tileAt(map, goal)?.walkable) return null; const open = [{ point: start, score: 0 }]; const came = new Map<string, Point>(); const cost = new Map([[key(start), 0]]); while (open.length) { open.sort((a, b) => a.score - b.score); const current = open.shift()!.point; if (key(current) === key(goal)) { const path: Point[] = []; let cursor = current; while (key(cursor) !== key(start)) { path.unshift(cursor); cursor = came.get(key(cursor))!; } return path; } for (const next of neighbors(map, current)) { const step = next.col !== current.col && next.row !== current.row ? Math.SQRT2 : 1; const nextCost = cost.get(key(current))! + step; if (nextCost < (cost.get(key(next)) ?? Infinity)) { cost.set(key(next), nextCost); came.set(key(next), current); open.push({ point: next, score: nextCost + distance(next, goal) }); } } } return null; }
export function resolveDestination(map: WorldMap, start: Point, requested: Point): Point | null { const target = clampPoint(map, requested); if (findPath(map, start, target)) return target; const reachable = reachableTiles(map, start); return reachable.sort((a, b) => distance(a, target) - distance(b, target) || a.row - b.row || a.col - b.col)[0] ?? null; }
