import type { Point, Settlement, WorldRoad } from './types';
import type { AuthoredTileEditor } from './authoredTiles';
import { generateRoutePoints } from './routes';
import { tileKey, cardinalNeighbors } from './worldCoordinates';
import { hash } from './terrain';
import { isRoadSurface } from './domainTiles';
export function connectSettlements(editor: AuthoredTileEditor, settlements: Settlement[], seed: number, countries: readonly { id: string }[]) {
  const roads: WorldRoad[] = [];
  const route = (a: Point, b: Point) => { const lead = (point: Point, other: Point) => { const s = settlements.find((candidate) => candidate.col === point.col && candidate.row === point.row); if (!s) return point; const horizontal = Math.abs(other.col - point.col) >= Math.abs(other.row - point.row), distance = s.radius + 1; return horizontal ? { col: point.col + Math.sign(other.col - point.col) * distance, row: point.row } : { col: point.col, row: point.row + Math.sign(other.row - point.row) * distance }; }; const from = lead(a, b), to = lead(b, a); const points = [...generateRoutePoints(seed, a, from), ...generateRoutePoints(seed, from, to).slice(1), ...generateRoutePoints(seed, to, b).slice(1)]; for (const point of points) { const old = editor.get(point); const bridge = (old?.kind ?? '') === 'water'; editor.put(point, { kind: bridge ? 'bridge' : 'road', walkable: true, groundKind: bridge ? 'water' : 'grass' }); } };
  const connect = (a: Settlement, b: Settlement) => { roads.push({ id: `road-${roads.length}`, settlementIds: [a.id, b.id] }); route(a, b); };
  countries.forEach((country, i) => { const own = settlements.filter((s) => s.countryId === country.id), capital = own.find((s) => s.kind === 'capital')!, cities = own.filter((s) => s.kind === 'city'); cities.forEach((city) => connect(capital, city)); own.filter((s) => s.kind === 'village').forEach((v, j) => connect(v, cities[j % cities.length]!)); if (i) connect(settlements.find((s) => s.countryId === countries[i - 1]!.id && s.kind === 'capital')!, capital); });
  return { roads, reopenRoadCorridors: () => roads.forEach((road) => { const a = settlements.find((s) => s.id === road.settlementIds[0])!, b = settlements.find((s) => s.id === road.settlementIds[1])!; route(a, b); }) };
}
export function normalizeRoadOverlaps(editor: AuthoredTileEditor, settlements: Settlement[], seed: number) {
  const routeTiles = new Set<string>(); for (const [id, tile] of editor.entries()) if (isRoadSurface(tile.kind)) routeTiles.add(id);
  const restore = (p: Point) => { const s = settlements.find((candidate) => p.col >= candidate.bounds.left && p.col <= candidate.bounds.right && p.row >= candidate.bounds.top && p.row <= candidate.bounds.bottom); if (!s) return editor.remove(p); const perimeter = p.col === s.bounds.left || p.col === s.bounds.right || p.row === s.bounds.top || p.row === s.bounds.bottom; if (perimeter && s.kind !== 'village') { const corner = (p.col === s.bounds.left || p.col === s.bounds.right) && (p.row === s.bounds.top || p.row === s.bounds.bottom); return editor.put(p, { kind: corner && s.kind === 'capital' ? 'tower' : 'wall', walkable: false, settlementId: s.id }); } editor.put(p, { kind: 'grass', walkable: true, settlementId: s.id }); };
  const anchors = [...routeTiles].map((id) => { const [col, row] = id.split(',').map(Number); return { col, row }; }).filter((p) => routeTiles.has(tileKey({ col: p.col + 1, row: p.row })) && routeTiles.has(tileKey({ col: p.col, row: p.row + 1 })) && routeTiles.has(tileKey({ col: p.col + 1, row: p.row + 1 }))).sort((a, b) => a.row - b.row || a.col - b.col);
  const canRemove = (point: Point) => { const neighbors = cardinalNeighbors(point).filter((n) => routeTiles.has(tileKey(n))); if (neighbors.length < 2 || neighbors.length === 2) return true; routeTiles.delete(tileKey(point)); const reachable = new Set([tileKey(neighbors[0]!)]), queue = [neighbors[0]!]; for (let i = 0; i < queue.length && !neighbors.every((n) => reachable.has(tileKey(n))); i += 1) for (const n of cardinalNeighbors(queue[i]!)) if (routeTiles.has(tileKey(n)) && !reachable.has(tileKey(n))) { reachable.add(tileKey(n)); queue.push(n); } routeTiles.add(tileKey(point)); return neighbors.every((n) => reachable.has(tileKey(n))); };
  for (const anchor of anchors) { const block = [anchor, { col: anchor.col + 1, row: anchor.row }, { col: anchor.col, row: anchor.row + 1 }, { col: anchor.col + 1, row: anchor.row + 1 }]; if (!block.every((p) => routeTiles.has(tileKey(p)))) continue; const candidates = block.filter((p) => !settlements.some((s) => s.col === p.col && s.row === p.row)).map((point) => ({ point, degree: cardinalNeighbors(point).filter((n) => routeTiles.has(tileKey(n))).length, preference: cardinalNeighbors(point).filter((n) => routeTiles.has(tileKey(n))).length === 2 ? 0 : 1, tie: hash(seed, point.col, point.row) })).sort((a, b) => a.preference - b.preference || a.degree - b.degree || a.tie - b.tie); const chosen = candidates.find(({ point }) => canRemove(point)); if (chosen) { routeTiles.delete(tileKey(chosen.point)); restore(chosen.point); } else throw new Error(`Unable to normalize route overlap at ${anchor.col},${anchor.row}`); }
}
